// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM_k7nSsx0RM92nZZwQeUbimCvg6RceRA',
    appId: '1:367355369302:web:7365ab1c719a99bb18e8f7',
    messagingSenderId: '367355369302',
    projectId: 'gharassist-37e4e',
    authDomain: 'gharassist-37e4e.firebaseapp.com',
    storageBucket: 'gharassist-37e4e.firebasestorage.app',
    measurementId: 'G-9NHZRMX4VR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiCEDl1HCFVXP6xq2Eva_0ha72nGO8Jzs',
    appId: '1:367355369302:android:0f67ff828f1a234818e8f7',
    messagingSenderId: '367355369302',
    projectId: 'gharassist-37e4e',
    storageBucket: 'gharassist-37e4e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmTVlXGvDpPiVR3TcOCahXVUUMUdtO2oY',
    appId: '1:367355369302:ios:cd88dbc7da03695a18e8f7',
    messagingSenderId: '367355369302',
    projectId: 'gharassist-37e4e',
    storageBucket: 'gharassist-37e4e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmTVlXGvDpPiVR3TcOCahXVUUMUdtO2oY',
    appId: '1:367355369302:ios:cd88dbc7da03695a18e8f7',
    messagingSenderId: '367355369302',
    projectId: 'gharassist-37e4e',
    storageBucket: 'gharassist-37e4e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCM_k7nSsx0RM92nZZwQeUbimCvg6RceRA',
    appId: '1:367355369302:web:a17da4970f41a4bd18e8f7',
    messagingSenderId: '367355369302',
    projectId: 'gharassist-37e4e',
    authDomain: 'gharassist-37e4e.firebaseapp.com',
    storageBucket: 'gharassist-37e4e.firebasestorage.app',
    measurementId: 'G-SB59FM112X',
  );
}
